config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/AboutMe'
  get 'static_pages/ContactMe'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Define the routes for the BlogPostController CRUD OPS
  get "/post/new", to: "blog_post#new", as: "new_post"
  post "/post", to: "blog_post#create", as: "blog_posts"
  get "/post/:id/edit", to: "blog_post#edit", as: "edit_post"
  patch "/post/:id", to: "blog_post#update", as: "blog_post"
  delete "/post/:id", to: "blog_post#delete"
  get "/post/:id", to: "blog_post#show", as: "post"

  # Define the route for the postnotfound page
  get "/postnotfound", to: "blog_post#postnotfound", as: "post_not_found"

  get "/about", to: "static_pages#AboutMe", as: "about_me"
  get "/contact", to: "static_pages#ContactMe", as: "contact_me"

  # Defines the root path route ("/")
  root "blog_post#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_rich_text :content

  validates :title, presence: true, length: { maximum: 100 }
  validates :content, presence: true, length: { maximum: 10000 }
  validates :tags, inclusion: { in: %w[frameworks update feature guide announcement], message: "%{value} is not a valid tag" }

  scope :sorted, -> { order(arel_table[:published_at].desc.nulls_last).order(updated_at: :desc) }
  scope :draft, -> { where(published_at: nil)}
  scope :published, -> { where("published_at <= ?", Time.current)}
  scope :scheduled, -> { where(" published_at > ?", Time.current)}

  def draft?
    published_at.nil?
  end

  def published?
    published_at? && published_at <= Time.current
  end

  def scheduled?
    published_at? && published_at > Time.current
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # Add :registerable to enable user registration
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/blog_post_controller.rb
class BlogPostController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :postnotfound]
  before_action :set_blog_post, only: [:edit, :update, :show, :delete]
  def index
    @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.published.sorted
    @pagy, @blog_posts = pagy(@blog_posts)
    rescue Pagy::OverflowError
      redirect_to root_path
      # params[:page] = 1
      # retry
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(post_params)
    if @blog_post.save
      redirect_to post_path(@blog_post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    rescue ActiveRecord::RecordNotFound
      redirect_to "/postnotfound/#{params[:id]}"
  end

  def update
    if @blog_post.update(post_params)
      redirect_to post_path(@blog_post)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    rescue ActiveRecord::RecordNotFound
      redirect_to post_not_found_path
  end

  def delete
    @blog_post.destroy
    redirect_to root_path
  end

  def postnotfound
  end

  private
  def post_params
    params.require(:blog_post).permit(:title, :content, :tags, :published_at)
  end

  def set_blog_post
    @blog_post = user_signed_in? ? BlogPost.find(params[:id]) : BlogPost.published.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to post_not_found_path
  end

  def authenticate_user!
    redirect_to new_user_session_path, alert: "You must sign up or sign in to continue" unless user_signed_in?
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def AboutMe
  end

  def ContactMe
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
  require 'pagy/extras/overflow'
  Pagy::DEFAULT[:overflow] = :last_page
  Pagy::DEFAULT[:items] = 14 # items per page
  Pagy::DEFAULT[:size]  = 9 # page size
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
  def tag_color(tag)
    case tag
    when 'news'
      'red'
    when 'update'
      'blue'
    when 'feature'
      'green'
    when 'guide'
      'teal'
    when 'announcement'
      'purple'
    else
      'gray'
    end
  end
end# frozen_string_literal: true

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_post/_form.html.erb
<%= form_with model: blog_post do |form| %>
  <section style="min-height: max-content; height: 100%; margin: 50px 0px;">
    <div style="margin-bottom: 10px;">
      <%= form.label :title, style: "display: block; margin-bottom: 5px;" %>
      <%= form.text_field :title, style: "width: 100%; padding: 8px; border: 1px solid #ccc; border-radius: 4px;" %>
    </div>
    <div style="margin-bottom: 10px; " class="editor">
      <%= form.label :content, style: "display: block; margin-bottom: 5px;" %>
      <%= form.rich_text_area :content, style: "width: 100%; padding: 8px; border: 1px solid #ccc; border-radius: 4px; min-height: 100px; height:auto; color:#112211;" %>
    </div>
    <% if form.object.errors.any? %>
      <div style="background-color: #f44336; color: white; padding: 10px 20px; border-radius: 4px; margin-bottom: 10px;">
        <ul style="margin: 0;">
          <% form.object.errors.full_messages.each do |msg| %>
            <li style="list-style: none"><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div style=" display: flex; flex-direction: column; gap: 30px; border: 1px solid #ccc; border-radius: 4px; padding: 5px; width: 100%;">
      <%= form.label :published_at  %>
      <div>
        <%= form.datetime_select :published_at, end_year: Time.now.year + 5 , include_blank: true %>
      </div>
    </div>

    <div style="margin-bottom: 10px;">
      <%= form.label :tags, style: "display: block; margin-bottom: 5px;" %>
      <%= form.select :tags, %w[frameworks update feature guide announcement], { include_blank: true }, { style: "width: 100%; padding: 8px; border: 1px solid #ccc; border-radius: 4px;" } %>
    </div>

    <div style="margin-top: 24px; display: flex; flex-direction: row; justify-content: center; align-items: center;">
      <%= form.button button_text, style: "background-color: #4CAF50; color: white; padding: 10px 20px; border: none; border-radius: 4px; cursor: pointer;" %>
    </div>
  </section>
<% end %>

app/views/blog_post/edit.html.erb
<body style="background-color: #F0F0F0; font-family: 'Candara Light', serif; font-size: 18px; color: #2E2F30; display: block; padding: 10px">
<nav style="display: flex; flex-direction: row; justify-content: space-between; align-items: center; margin-top: 10px; padding-left: 10px; padding-right: 10px; max-width: 100vw">
  <h1>Edit Post <%= @blog_post.id %></h1>
  <%=
    button_to "Delete Post",
    @blog_post,
    method: :delete,
    form: {style: "display: inline;"},
    style: "background-color: #f44336; color: white; padding: 10px 20px; border: none; border-radius: 4px; cursor: pointer;" ,
    data: { turbo_confirm: "Are you sure you want to delete this post?" }
  %>
</nav>

<%= render partial: "form", locals: {blog_post: @blog_post, button_text: "Edit Post"} %>

</body>

app/views/blog_post/index.html.erb
<head>
  <title>Blog Post</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "pagy", "data-turbo-track": "reload" %>
</head>
<main style=" display: block; max-width: 1216px; width: 100%">
  <h1 style="display: flex; flex-direction: row; justify-content: center; align-items: center; margin: 55px 0px; padding: 10px 0px; max-font-size: 244px; font-size: 200px; line-height: normal; text-transform: capitalize; border-top: 2px solid white; border-bottom: 2px solid white; width: 100%; max-width: 1216px;">
      DEV BLOG
  </h1>
  <section class="blogpostclass">
    <% @blog_posts.each do |blog_post| %>
      <div style="padding: 25px; border: solid 2px #2E2F30; border-radius: 16px; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">
        <% if blog_post.draft? %>
          <div style="background: lightslategrey; border: 3px solid darkslategrey; border-radius: 24px; box-shadow: 1px 2px 2px gray; width: fit-content; padding: 8px; display: flex; justify-content: flex-start; align-items: center; margin-top: 10px; font-family: Helvetica Neue, Helvetica, Arial, sans-serif; color: #666666; font-style: italic; gap: 4px;">
            Draft
            <i class="fas fa-drafting-compass"></i>
          </div>
        <% elsif blog_post.scheduled? %>
          <div style=" background: darkseagreen; border: 3px solid seagreen; border-radius: 24px; box-shadow: 1px 1px 1px forestgreen; width: fit-content; padding: 8px; display: flex; justify-content: flex-start; align-items: center; margin-top: 10px; font-family: Helvetica Neue, Helvetica, Arial, sans-serif; color: #666666; font-style: italic; gap: 4px;">
            Scheduled Post
            <i class="fas fa-stopwatch"></i>
          </div>
        <% end %>
        <h2 style="font-weight: bold">
          <%= link_to blog_post.title, post_path(blog_post) %>
        </h2>
        <p style=" color: black; background: #090D1F;"><%= blog_post.content %></p>
        <p style="background: <%= tag_color(blog_post.tags) %>; color: white; padding: 5px 8px; border: none; border-radius: 24px; margin-top: 14px; width: fit-content"><%= blog_post.tags %></p>
      </div>
    <% end %>
  </section>
  <footer style="width: 100%; display: flex; justify-content: center; align-items: center; padding-top: 10px; padding-bottom: 10px; border-top: 1px solid #EAECF0;">
    <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
  </footer>
</main>

app/views/blog_post/new.html.erb
<body style="background-color: #F0F0F0; font-family: 'Candara Light', serif; font-size: 18px; color: #2E2F30; display: block; padding: 10px">
<h1>Create new Post</h1>

 <%= render partial: "form", locals: {blog_post: @blog_post, button_text: "Create Post"} %>

</body>

app/views/blog_post/postnotfound.html.erb
<head>
  <title>Post Not Found</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'postnotfound', 'data-turbolinks-track': 'reload' %>
</head>
<body style="background: #000;display: flex;height: 100vh;">
  <h3 style="position: absolute; top: 100px; left: 43vw; color: #BBBBBB">Post not found <%= link_to 'Go Back', root_path, class: 'btn btn-primary' %></h3>
  <figure>
<!--    <div class="sad-mac"></div>-->
    <figcaption>
      <span class="sr-text">Error 404: Post not found</span>
      <span class="e"></span>
      <span class="r"></span>
      <span class="r"></span>
      <span class="o"></span>
      <span class="r"></span>
      <span class="_4"></span>
      <span class="_0"></span>
      <span class="_4"></span>
      <span class="n"></span>
      <span class="o"></span>
      <span class="t"></span>
      <span class="f"></span>
      <span class="o"></span>
      <span class="u"></span>
      <span class="n"></span>
      <span class="d"></span>
    </figcaption>
  </figure>
</body>

app/views/blog_post/show.html.erb
<main style="display: flex; flex-direction: column; min-height: 90vh; height: fit-content; margin: 10px 0px; gap: 24px; padding: 10px; width: 100%; max-width: 1216px;">
  <div style="display: flex; flex-direction: column; justify-content: center; align-items: center; width: 100%; max-width: 1216px; ">
    <h1 style="font-weight: bold; width: 100%; margin: 24px 0px;">
      <%= @blog_post.title %>
    </h1>
    <span style="width: 100%; font-weight: lighter; color: #6b7280;">
      <%= @blog_post.updated_at.strftime("%d %B, %Y at %I:%M %p") %>
    </span>
  </div>
  <div style="display: flex; flex-direction: row; justify-content: flex-start; align-items: center; border-bottom: 1px solid #6b7280; border-top: 1px solid #6b7280; margin: 24px 0px; height: 60px;">
    <% if @blog_post.draft? %>
      <div style="background: lightslategrey; border: 3px solid darkslategrey; border-radius: 24px; box-shadow: 1px 2px 2px gray; width: fit-content; padding: 8px; display: flex; justify-content: flex-start; align-items: center; margin-top: 10px; font-family: Helvetica Neue, Helvetica, Arial, sans-serif; color: #666666; font-style: italic; gap: 4px;">
        Draft
        <i class="fas fa-drafting-compass"></i>
      </div>
    <% elsif @blog_post.scheduled? %>
      <div style="background: darkseagreen; border: 3px solid seagreen; border-radius: 24px; box-shadow: 1px 1px 1px forestgreen; width: fit-content; padding: 8px; display: flex; justify-content: flex-start; align-items: center; margin-top: 10px; font-family: Helvetica Neue, Helvetica, Arial, sans-serif; color: #666666; font-style: italic; gap: 4px;">
        Scheduled Post
        <i class="fas fa-stopwatch"></i>
      </div>
    <% end %>
    <span style="background: <%= tag_color(@blog_post.tags) %>; width: fit-content; color: white; padding: 5px 8px; border: none; border-radius: 24px; margin: 14px;"><%= @blog_post.tags %></span>
    <div style="display: flex; flex-direction: row; gap: 6px; align-items: center;">
      ↳
      <div class= "image-container">
        <%= image_tag('newme.jpg', alt: 'Suvan GS') %>
      </div>
      <p>Suvan Gowri Shanker</p>
    </div>
    <% if user_signed_in? %>
      <%= link_to edit_post_path do %>
        <i class="far fa-edit" style="margin: 0px 10px;"></i>
      <% end %>
      <%= button_to @blog_post, method: :delete, form: {style: "display: inline; background: #090D1F; margin: 0px 10px; cursor: pointer;"}, style: "background: #090D1F; color: red; cursor: pointer;", data: { turbo_confirm: "Are you sure you want to delete this post?" } do %>
        <i class="far fa-trash-alt"></i>
      <% end %>
    <% end %>
  </div>
  <p style="font-family: 'Candara Light',serif; font-size: 18px; color: #2E2F30;">
    <%= @blog_post.content %>
  </p>
</main>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Suvan's Blog</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="margin: 10px 0px; display: flex; flex-direction: column; align-items: center;">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% unless current_page?(new_user_session_path) || current_page?(post_not_found_path) %>
      <nav style="width: 100%; max-width: 1216px; display: flex; justify-self: center; justify-content: space-between; align-items: center; gap: 10px; margin-top: 10px;">
        <%= link_to "Suvan GS" , root_path, style: "font-size: 20px; font-weight: bold; line-height: 24px;" %>
        <div style="display: flex; flex-direction: row; gap: 24px; align-items: center">
          <div style="display: flex; flex-direction: row; gap: 14px; color: white">
            <%= link_to "About", about_me_path %>
            <%= link_to "Contact", contact_me_path %>
          </div>
          <% if user_signed_in? %>
            <!-- Profile Link -->
            <%#= link_to edit_user_registration_path, style: "background-color: #f44336; color: white; padding: 10px 20px; border: none; border-radius: 4px; cursor: pointer; text-decoration: none; position: relative;" do %>
  <!--            <div class="icon-text-container">-->
  <!--              <i class="fas fa-user"></i>-->
  <!--              <span class="hover-text">Profile</span>-->
  <!--            </div>-->
            <%# end %>

            <!-- New Post Link -->
            <%= link_to new_post_path, class: "icon-text-container" do %>
              <i class="fas fa-feather-alt"></i>
              <span class="hover-text">New Post</span>
            <% end %>
            <%= button_to destroy_user_session_path, method: :delete, form: {class:"icon-text-container"}, style: "color: #D2042D; background: transparent ", data: { turbo_confirm: "Do you wish to sign out?"} do %>
                <i class="fas fa-sign-out-alt"></i>
                <span class="hover-text">Sign Out</span>
            <% end %>
          <% else %>
            <%#= link_to 'Sign up', new_user_registration_path, style: "background-color: #4CAF50; color: white; padding: 10px 20px; border: none; border-radius: 4px; cursor: pointer; text-decoration: none;" %>
            <%= link_to 'Sign in', new_user_session_path, style: "background-color: #008CBA; color: white; padding: 10px 20px; border: none; border-radius: 4px; cursor: pointer; text-decoration: none;" %>
          <% end %>
        </div>
      </nav>
    <% end %>
    <%= yield %>
  <footer style="display: flex; width: 100%; max-width: 1216px; flex-direction: row; justify-content: space-between; align-items: center; gap: 14px; font-size: 20px;">
    <p>
      SuvanGS © <%= Time.now.year %>
    </p>
    <div style="display: flex; flex-direction: row; flex-wrap: wrap; gap: 14px; align-items: center;">
      <a href="https://www.instagram.com/suvangs/"><i class="fab fa-instagram"></i></a>
      <a href="https://github.com/greeenboi"><i class="fab fa-github"></i></a>
      <a href="https://suvangs.vercel.app"><i class="fas fa-globe"></i></a>
      <a href="https://www.linkedin.com/in/suvan-gowri-shanker-596943261/"><i class="fab fa-linkedin-in"></i></a>
    </div>
  </footer>
  </body>
</html>

<script>
    function redirectToUrl(path){
        window.location.href = path;
    }
</script>

app/views/static_pages/AboutMe.html.erb
<h1>StaticPages#AboutMe</h1>
<p>Find me in app/views/static_pages/AboutMe.html.erb</p>

app/views/static_pages/ContactMe.html.erb
<h1>StaticPages#ContactMe</h1>
<p>Find me in app/views/static_pages/ContactMe.html.erb</p>